    public enum AudioLibSounds {
        sfx_AR,
        sfx_GrenadeBoom,
        sfx_GrenadeLauncher,
        sfx_GrenadePin,
        sfx_HealthPack,
        sfx_Hitmarker,
        sfx_Reload,
        sfx_Shotgun,
        sfx_Slash,
        sfx_SMG,
        sfx_WoodenBox,
        sfx_Meaty,
        sfx_WinBrass,
        sfx_EnemyGun,
        sfx_HurtAll,
        sfx_Hurt2,
        sfx_Hurt3,
        sfx_Hurt4,
        sfx_Gauss,
        sfx_EnvHit,
        sfx_GrenadeWhistle,
        sfx_LMG,
        sfx_Gore,
        sfx_GrenadeThrow
    }
    public enum AudioLibMusic {
        music_Battlefield,
        music_Menu
    }
